### PR TITLE
Add 'explore all courses' option to home page

### PR DESCRIPTION
**Pull request by bensaine**
Simple addition stemming from a small annoyance I was having with the UX. The 'explore all courses' seems like it is a very common use-case, instead of needing two clicks (input > "Explore all courses"), simply add an option below the search bar on the homepage for quick, one-click only, access. Option remains on input as well.

image

### CODE REVIEW

**Comment by 39bytes** [comment]
I think that maybe the `or explore all courses` link could be moved up to be closer to the search bar so that when you have the search results open there isn't two clickable elements next to each other that do the same thing.
Thoughts?

**Comment by 39bytes** [comment]
> Good point. Also, I am debating between `text-sm` and `text-base`, thoughts?

`text-base` is fine for desktop, `text-sm` would work better for mobile.
Also, it would probably be good to shrink the gap between the "Explore thousands of..." and the search bar since the style changes makes it slightly larger than before.

**Comment by bensaine** [comment]
ok, done

**Comment by 39bytes** [comment]
> ok, done

thanks, looks good :+1:

**Review by 39bytes — APPROVED** [review]

**Pull request merged**
