### PR TITLE
Add Discord link to the contacts

### PR DESCRIPTION
**Pull request by SamZhang02**
Thoughts on putting the Discord server instead of an admin email?

### CODE REVIEW

**Comment by 39bytes** [comment]
why not both?

**Comment by SamZhang02** [comment]
> why not both?

Because I wasn't sure if `admin@mcgill.course` is a thing yet :ICANT:, @terror is the email live? 
I'm ok with both 📈

**Comment by terror** [comment]
> > why not both?
> 
> Because I wasn't sure if `admin@mcgill.course` is a thing yet :ICANT:, @terror is the email live? I'm ok with both 📈

admin@mcgill.courses is live, we should keep both

**Comment by SamZhang02** [comment]
bet, gonna add it back beside the discord link then

**Review by terror — APPROVED** [review]

**Pull request merged**
